/// <summary>
/// Complete DMVC Controller example with Active Record.
/// Demonstrates: MVCPath attributes, Active Record, serialization,
/// error handling, guard clauses and memory management.
/// </summary>
unit Example.Controller.Customer;

interface

uses
  MVCFramework,
  MVCFramework.Commons,
  MVCFramework.Serializer.Commons;

type
  // =========================================================================
  // Active Record Model
  // =========================================================================

  [MVCTable('customers')]
  [MVCNameCase(ncLowerCase)]
  TCustomer = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FId: Integer;

    [MVCTableField('name')]
    FName: string;

    [MVCTableField('cpf')]
    FCpf: string;

    [MVCTableField('e-mail')]
    FEmail: string;

    [MVCTableField('status')]
    FStatus: Integer;

    [MVCTableField('created_at')]
    FCreatedAt: TDateTime;
  public
    /// <summary>Validates customer data before saving.</summary>
    function IsValid: Boolean;

    property Id: Integer read FId write FId;
    property Name: string read FName write FName;
    property Cpf: string read FCpf write FCpf;
    property Email: string read FEmail write FEmail;
    property Status: Integer read FStatus write FStatus;
    property CreatedAt: TDateTime read FCreatedAt write FCreatedAt;
  end;

  // =========================================================================
  // Controller
  // =========================================================================

  [MVCPath('/api/customers')]
  TCustomerController = class(TMVCController)
  public
    /// <summary>Returns all customers.</summary>
    [MVCPath]
    [MVCHTTPMethod([httpGET])]
    [MVCProduces(TMVCMediaType.APPLICATION_JSON)]
    procedure GetAll;

    /// <summary>Returns a customer by ID.</summary>
    [MVCPath('/($id)')]
    [MVCHTTPMethod([httpGET])]
    [MVCProduces(TMVCMediaType.APPLICATION_JSON)]
    procedure GetById(const AId: Integer);

    /// <summary>Creates a new customer.</summary>
    [MVCPath]
    [MVCHTTPMethod([httpPOST])]
    [MVCConsumes(TMVCMediaType.APPLICATION_JSON)]
    [MVCProduces(TMVCMediaType.APPLICATION_JSON)]
    procedure CreateCustomer;

    /// <summary>Updates an existing customer.</summary>
    [MVCPath('/($id)')]
    [MVCHTTPMethod([httpPUT])]
    [MVCConsumes(TMVCMediaType.APPLICATION_JSON)]
    procedure UpdateCustomer(const AId: Integer);

    /// <summary>Remove a customer by ID.</summary>
    [MVCPath('/($id)')]
    [MVCHTTPMethod([httpDELETE])]
    procedure DeleteCustomer(const AId: Integer);

    /// <summary>Search customers by name (partial).</summary>
    [MVCPath('/search')]
    [MVCHTTPMethod([httpGET])]
    [MVCProduces(TMVCMediaType.APPLICATION_JSON)]
    procedure Search;
  end;

implementation

uses
  System.SysUtils,
  System.DateUtils,
  MVCFramework.ActiveRecord,
  MVCFramework.Logger;

const
  MIN_NAME_LENGTH = 3;
  CPF_LENGTH = 11;

// =========================================================================
// TCustomer
// =========================================================================

function TCustomer.IsValid: Boolean;
begin
  Result := (FName.Trim.Length >= MIN_NAME_LENGTH) and
            (FCpf.Length = CPF_LENGTH);
end;

// =========================================================================
// TCustomerController
// =========================================================================

procedure TCustomerController.GetAll;
var
  LCustomers: TMVCActiveRecordList;
begin
  LCustomers := TMVCActiveRecord.SelectRQL<TCustomer>('', 100);
  Render<TCustomer>(LCustomers);
end;

procedure TCustomerController.GetById(const AId: Integer);
var
  LCustomer: TCustomer;
begin
  LCustomer := TMVCActiveRecord.GetByPK<TCustomer>(AId);

  // Guard clause — not found
  if not Assigned(LCustomer) then
  begin
    Render(HTTP_STATUS.NotFound, 'Customer not found');
    Exit;
  end;

  Render(LCustomer);
end;

procedure TCustomerController.CreateCustomer;
var
  LCustomer: TCustomer;
begin
  LCustomer := Context.Request.BodyAs<TCustomer>;
  try
    // Guard clause — validation
    if not LCustomer.IsValid then
    begin
      Render(HTTP_STATUS.BadRequest, 'Invalid customer data');
      LCustomer.Free;
      Exit;
    end;

    LCustomer.CreatedAt := Now;
    LCustomer.Status := 1; // Active
    LCustomer.Insert;

    Render201Created('/api/customers/' + LCustomer.Id.ToString);
  except
    on E: Exception do
    begin
      Log.Error('[CreateCustomer]' + E.Message, 'customer');
      LCustomer.Free;
      raise;
    end;
  end;
end;

procedure TCustomerController.UpdateCustomer(const AId: Integer);
var
  LCustomer: TCustomer;
  LExisting: TCustomer;
begin
  // Guard clause — check if it exists
  LExisting := TMVCActiveRecord.GetByPK<TCustomer>(AId);
  if not Assigned(LExisting) then
  begin
    Render(HTTP_STATUS.NotFound, 'Customer not found');
    Exit;
  end;
  LExisting.Free;

  LCustomer := Context.Request.BodyAs<TCustomer>;
  try
    LCustomer.Id := AId;

    if not LCustomer.IsValid then
    begin
      Render(HTTP_STATUS.BadRequest, 'Invalid customer data');
      LCustomer.Free;
      Exit;
    end;

    LCustomer.Update;
    Render(HTTP_STATUS.OK, 'Customer updated');
  except
    on E: Exception do
    begin
      Log.Error('[UpdateCustomer]' + E.Message, 'customer');
      LCustomer.Free;
      raise;
    end;
  end;
end;

procedure TCustomerController.DeleteCustomer(const AId: Integer);
var
  LCustomer: TCustomer;
begin
  LCustomer := TMVCActiveRecord.GetByPK<TCustomer>(AId);

  // Guard clause — not found
  if not Assigned(LCustomer) then
  begin
    Render(HTTP_STATUS.NotFound, 'Customer not found');
    Exit;
  end;

  try
    LCustomer.Delete;
    Render(HTTP_STATUS.NoContent, '');
  finally
    LCustomer.Free;
  end;
end;

procedure TCustomerController.Search;
var
  LSearchTerm: string;
  LCustomers: TMVCActiveRecordList;
begin
  LSearchTerm := Context.Request.Params['q'];

  // Guard clause — mandatory parameter
  if LSearchTerm.Trim.IsEmpty then
  begin
    Render(HTTP_STATUS.BadRequest, 'Query parameter "q" is required');
    Exit;
  end;

  LCustomers := TMVCActiveRecord.Where<TCustomer>(
    'name LIKE ?', ['%' + LSearchTerm + '%']);
  Render<TCustomer>(LCustomers);
end;

end.

